codecov:
  token: 07f746f7-0482-4ee0-9ab9-b5e3f1e2a540
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: yes

github_checks:
  annotations: false