version: 2.1
orbs:
  typescript: vidsy/typescript@1.0.0

jobs:
  master:
    branch: master
    docker:
      - image: 'node:12.18.3'
    steps:
      - checkout
      - run: node --version
      - run: yarn --version
      - run:
          name: Install Modules
          command: |
              yarn install;
      - run:
          name: Test
          command: yarn test
          environment:
            NODE_OPTIONS: --max_old_space_size=5000
            NODE_ENV: test
      - run:
          name: Upload Coverage
          command: yarn coverage:upload
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy to Production
          command: scp -r ./ $SSH_USER@$SSH_LOCATION:$SSH_PROJECT_DIR
