version: 2.1


jobs:
  build:
    docker:
      source:
        repository: node
        tag: 12.13.0
    steps:
      - checkout
      - run:
          name: Install Modules
          command: yarn install
      - run:
          name: Install Modules
          command: ls -asl ./node_modules/ts-jest
      - run:
          name: Test
          command: yarn test
