version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:12.13.0'
    steps:
      - checkout
      - run:
          name: Install Node Modules
          command: yarn && pwd
      - run:
          name: Test
          command: yarn test
