version: 2.1


jobs:
  build:
    docker:
      - image: 'circleci/node:12.18.3'
    steps:
      - checkout
      - run:
          name: Install Node Modules
          command: node -v && npm --v && yarn --v
