version: 2.1
orbs:
  typescript: vidsy/typescript@1.0.0

jobs:
  build:
    docker:
      - image: 'node:12.18.3'
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: yarn --version
      - run:
          name: Install Modules
          command: |
              npm install -g typescript
              yarn install;
              ls -asl ./node_modules;
      - run:
          name: Test
          command: yarn test
