version: 2.1


jobs:
  build:
    docker:
      - image: 'circleci/node:12.18.3'
    steps:
      - checkout
      - run:
          name: Install Modules
          command: yarn install
      - run:
          name: Test
          command: yarn test
