version: 2.1
orbs:
  typescript: vidsy/typescript@1.0.0

jobs:
  build:
    docker:
      - image: 'node:12.18.3'
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run:
          name: Install Modules
          command: |
              npm install;
      - run:
          name: Test
          command: npm test
